# Generated by Django 6.0.3 on 2026-04-14 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lf_itse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expedientes', models.BooleanField(default=False)),
                ('licencias', models.BooleanField(default=False)),
                ('itse', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('fecha_digitacion', models.DateTimeField()),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_lf_itse', to=settings.AUTH_USER_MODEL)),
                ('user_digitador', models.ForeignKey(db_column='user_id_digitador', on_delete=django.db.models.deletion.PROTECT, related_name='perfiles_digitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios_perfiles',
            },
        ),
    ]
