# Generated by Django 6.0.3 on 2026-04-14 17:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lf_itse', '0002_usuarioperfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoprocedimientotupa',
            name='plazo_atencion',
        ),
        migrations.AddField(
            model_name='tipoprocedimientotupa',
            name='fecha_digitacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tipoprocedimientotupa',
            name='requiere_itse',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipoprocedimientotupa',
            name='requiere_lf',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipoprocedimientotupa',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
