# Generated by Django 6.0.3 on 2026-04-14 19:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lf_itse', '0004_set_usuario_not_null_tipoproc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeriadoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feriado', models.DateField(unique=True)),
                ('fecha_digitacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feriados_anuales',
                'ordering': ['feriado'],
            },
        ),
        migrations.CreateModel(
            name='FeriadoRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
            ],
            options={
                'db_table': 'feriados_recurrentes',
                'ordering': ['mes', 'dia'],
                'constraints': [models.UniqueConstraint(fields=('dia', 'mes'), name='uq_feriados_rec_dia_mes')],
            },
        ),
    ]
