# Generated by Django 6.0.3 on 2026-04-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lf_itse', '0005_feriados_anuales_recurrentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Prefiero no decirlo')], default='X', max_length=1),
        ),
    ]
