# Generated by Django 6.0.3 on 2026-04-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lf_itse', '0006_add_sexo_to_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumentoidentidad',
            name='es_para_juridica',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipodocumentoidentidad',
            name='es_para_natural',
            field=models.BooleanField(default=True),
        ),
    ]
