# Generated by Django 6.0.3 on 2026-04-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lf_itse', '0007_add_es_para_natural_juridica_to_tipo_documento_identidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
